---
title: "Explore VCF"
author: "AL"
date: "1 Apr 2021"
output:
  html_document:
    toc: true
    number_sections: true
    toc_float: true
editor_options:
  chunk_output_type: console
---

# Summary

- Script shows examples of multi-allelic sites  
- All * in Alt are multiallelic  

<style>
pre{
  overflow-x: auto;
}
pre code{
  word-wrap: normal;
  white-space: pre;
}
s</style>

```{r echo=F}
options(width=999)
```

# Start section

```{r}

Sys.time()
rm(list=ls())
graphics.off()
gc()

```

# Read data

```{r}

data_folder <- "/home/share/data/s02_split_multiallelic_sites"
data_file <- "zhang_hg38.bwa.QC.MA-flag.MA-split.annotations.txt"
data.df <- read.table(file.path(data_folder,data_file),
                      header=F,sep="\t",quote="")

head(data.df)
#View(head(data.df))

colnames(data.df) <- c("chr","pos","id","ref","alt","filter","qual","info")

dim(data.df)
str(data.df)

rm(data_file)

```

# Multiallelic sites

```{r}

table(data.df$info, useNA = "always")

x <- data.df$info == "MULTIALLELIC"
sum(x)

y <- data.df[x,]
head(y)
#View(y)

y[12:21,]

sum(y$alt=="*")
sum(data.df$alt=="*")

rm(x,y)

```

# Save data

```{r}

save(data.df,file=file.path(data_folder,"s05_explore_vcf.RData"))

```

# Final section

```{r}
ls()
gc()
Sys.time()
sessionInfo()
```
